use crate::db::turso;
use crate::models::note::{ShareNote, ShareNoteInput};
use chrono::Utc;

async fn connection() -> Result<libsql::Connection, String> {
  let conn = turso::connect().await?;
  turso::create_table(&conn).await?;
  Ok(conn)
}

#[tauri::command]
pub async fn turso_create_table() -> Result<(), String> {
  let conn = turso::connect().await?;
  turso::create_table(&conn).await
}

#[tauri::command]
pub async fn turso_create_share_note(input: ShareNoteInput) -> Result<ShareNote, String> {
  let now = Utc::now().to_rfc3339();
  let note = ShareNote {
    // SQLite row IDs are signed 64-bit values. Microseconds provide an ID that
    // is generated by the backend, so callers never need to manage it.
    id: Utc::now().timestamp_micros(),
    title: input.title.trim().to_string(),
    content: input.content,
    links: input.links,
    created_at: now.clone(),
    updated_at: now,
  };

  if note.title.is_empty() {
    return Err("Title is required".to_string());
  }

  let conn = connection().await?;
  turso::insert(&conn, &note).await?;
  Ok(note)
}

#[tauri::command]
pub async fn turso_insert_share_note(note: ShareNote) -> Result<(), String> {
  let conn = connection().await?;
  turso::insert(&conn, &note).await
}

#[tauri::command]
pub async fn turso_list_share_notes() -> Result<Vec<ShareNote>, String> {
  let conn = connection().await?;
  turso::list_notes(&conn).await
}

#[tauri::command]
pub async fn turso_get_share_note(id: i64) -> Result<Option<ShareNote>, String> {
  let conn = connection().await?;
  turso::get_note(&conn, id).await
}

#[tauri::command]
pub async fn turso_update_share_note(note: ShareNote) -> Result<(), String> {
  if note.title.trim().is_empty() {
    return Err("Title is required".to_string());
  }
  let conn = connection().await?;
  turso::update_note(&conn, &note).await
}

#[tauri::command]
pub async fn turso_delete_share_note(id: i64) -> Result<(), String> {
  let conn = connection().await?;
  turso::delete_note(&conn, id).await
}
